### ISSUE TITLE
Two Meanings of "I"

### ISSUE THREAD

**Issue by Cluedrew** [Labdabeta/vns#11]
When interpreting the instructions there are two possible meanings for "I" . A 10-bit signed (2's complement) value or a 20-bit unsigned value. Already I have found myself stumbling to try and talk about the difference between the two without using the longer description. I feel the distinction between the two is significant as it changes both where the value is in the instruction and how it is interpreted.

So I propose the two immediate values are given unique names as the registers have. I recommend S and U for signed and unsigned immediate values.

Some other possibilities:
- I & N (Integer and Natural) Conflicts with opcode, although it could be changed.
- I & L (Immediate & Long Immediate)
- S & L (Short Immediate & Long Immediate)

**Comment by Labdabeta** [comment]
Now there is only 1 meaning of "I". The old documentation is outdated and slated for either recreation or deletion. In the current instructions (which are up to date) "I" is the immediate value. No operations reference the immediate register (the 'small immediate') but it can be used in any instruction which takes a register.
