### ISSUE TITLE
Query Nearest Flag Command

### ISSUE THREAD

**Issue by Cluedrew** [Labdabeta/vns#16]
This issue's main purpose is to introduce two new commands:
NSG a, b, c (Nearest Support Grid)
NTG a, b, c (Nearest Tactical Grid)
Each of which finds the nearest flag (space on the grids) of the same value stored in register "a" and stores the x & y coordinates in b & c. This is the main issue however to support it there are the following suggestions.

Get rid of the flag grid (as it has odd name out) and redistribute the instructions that work with it to work with the tactical or support grids. The two grids can then be the two "flag grids" to identity the pair. Another change that might useful is to move the G in the flag grid related instructions to the front of the commands so they are more identifiable as a group.

The rational for this is the low popularity of the flag grids. All discussions I have had about them people have not used the grids because communicating with normal coordinates is faster than marking a location on the grid and then searching for it. The low popularity of the instructions is also why I feel the existing commands could be renamed.

**Comment by Labdabeta** [comment]
Alternative solution: Remove the grids entirely. Replace them with advanced query commands. Note that some units have 6 grid operations, 4, 2, or none. These would be replaced with (most likely):

 - Query Setup (Mortar, Engineer, MG, Scout, Rifle)
 - Query Moving (Mortar, Engineer, MG, Scout, Rifle)
 - Query Shooting (Mortar, MG, Scout, Rifle)
 - Query Prone (Mortar, MG, Scout, Rifle)
 - Query Hidden (Mortar, Rifle)
 - Query Retreating or Summoned (Mortar, Rifle)
