### ISSUE TITLE
Downgrade Instructions Do Not Work as Intended

### ISSUE THREAD

**Issue by Cluedrew** [Labdabeta/vns#18]
The first problem is quite simple, downgrading a maxed upgrade slot kills the unit.

The second one I was very tempted to abuse, but I limited myself to making a very effective example:
[miner.vns](https://github.com/Labdabeta/vns/files/1565944/miner.vns.txt). For reference it produces resource points 8 times faster than a max clock captain using GVL repeatedly, and sets itself up a lot faster. It is also not limited to the captain or clock speed.

(I tested both. Clock speed is significantly more effective than the others because of high speed and it produces twice as much per cycle. However getting more units involved would break things even more.)

**Comment by Cluedrew** [comment]
Incidentally, I found this bug while looking into an issue that caused my units to die while trying to max an upgrade. However I have not looked into that yet.

**Comment by Labdabeta** [comment]
Seems like off by one in boards.adb for try upgrade. cost probably miscalculated. Will look into it further.
