### ISSUE TITLE
Maxing An Upgrade (with max instruction) Kills Unit

### ISSUE THREAD

**Issue by Cluedrew** [Labdabeta/vns#23]
```
died due to Exception name: CONSTRAINT_ERROR
Message: boards.adb:791 overflow check failed
```
I think it is trying to upgrade past level 4.

**Comment by Cluedrew** [comment]
Also I don't know the code well enough to do this myself, but I think you should consider:
```
type Upgrade_Type is (Cache_Size, Cache_Type, Branch_Predictor, CPU_Speed);
type Upgrade_Level is (Level_0, Level_1, Level_2, Level_3, Level_4);
Upgrade_Cost : constant array (Upgrade_Type, Upgrade_Level) of Resource_Points := (...);
```
Which should (almost) quarter the amount of code you have for upgrade instructions.

**Comment by Labdabeta** [comment]
That suggestion is somewhat valid, and I may consider doing that, but for now its easy enough to fix as a once-of. It is also a bit more explicit so it makes it a bit easier to debug when confused.
