### ISSUE TITLE
Ambiguous Interactions with Death

### ISSUE THREAD

**Issue by Cluedrew** [Labdabeta/vns#24]
There are a lot of questions about death and not just the metaphysical ones.

- Is a dead unit visible? If it dies while not visible? (relevant to WHR)
- Does a dead unit have a location? (relevant to WHR and mortar special registers)
- Is a unit at a spot once it has passed away? (relevant to WHO)
- Can a unit be close to another? (relevant to machine gunner and scout registers)
- Can a dead unit be set up? Camouflaged? Moving? Shooting? (If they were when they died?)

The manual doesn't specify and I noticed a couple cases where things did not match what I expected. But I'm not sure if that is what is intended or not.

**Comment by Labdabeta** [comment]
The current setup is supposed to be that dead units can't be found by any command, but their properties can still be directly queried. I will try to compile a list of relevant commands either tonight or tomorrow and add a section to the instructions. Let me know if you find any discrepancies.

**Comment by Cluedrew** [comment]
OK, so far they seem invisible to WHO and WHR. The special registers seem to target corpses, or are left as is I haven't experimented enough to tell, although I'm not sure what the target time of "nothing to shoot" is, a negative number might make more sense but I think (near) infinite time might be easier to check.

**Comment by Cluedrew** [comment]
I did some poking and it does seem to target dead units. Not the closest though, it seems to go by unit id.
