### ISSUE TITLE
DIR skips third value if given 2 direct coordinates

### ISSUE THREAD

**Issue by jchilibe** [Labdabeta/vns#31]
When using the command DIR r1, 2, 3 for example, using numerical coordinates instead of registers, the 3 is instead read as a 0 and the corresponding (incorrect) DIR is output. This does not occur when either of the coordinate values is a register.

**Comment by Labdabeta** [comment]
Unfortunately this is not a bug. There is only 1 immediate register, so you can only have 1 immediate value in each command. As such to achieve `DIR r1, 2, 3` you would have to use `ADD r2, r0, 2 DIR r1, r2, 3`.
