### ISSUE TITLE
Units Disappearing on WLK and RUN

### ISSUE THREAD

**Issue by Cluedrew** [Labdabeta/vns#6]
I ran my test AI (only two units did anything, just getting it compiled) however the units that move all disappear. One was a captain trying to execute a WLK command, the other was a scout trying to RUN. I ran the command until everything vanished and one extra frame and put the results in [error-report.txt](https://github.com/Labdabeta/vns/files/1493425/error-report.txt).

**Comment by Labdabeta** [comment]
Note: this is a case of wrong assembly. If you move in an invalid direction you die. 0 is an invalid direction. If you execute `wlk 1` it assumes that you want to execute `wlk` with an immediate address of 1. Thus A is 0 and so you try to `wlk r0, r0, r0`. Remember that wlk stores X and Y but you can ignore them with r0. Thus the correct way to walk north is `wlk 1, r0, r0` **not** `wlk 1`.
